### ISSUE TITLE
Cancelling faction switch effs some stuff up

### ISSUE THREAD

**Issue by kulars** [crackerbox42/legion-builder#1]
Button state gets messed up a little when you click the other faction but then do Cancel in the popup - the faction button you just clicked still looks gray and stops responding to future clicks, as if you clicked Ok instead of Cancel. If you do actually want to switch factions now you have to "switch" to the one you're really already on first to reset the state.

(Encountered in Firefox 59.0.3 on Windows 10)

**Comment by kulars** [comment]
I DEMAND THUIS BEF IXED IMEDAITELY

**Comment by crackerbox42** [comment]
I FIXED TEH BUG AS REQEASTEd
